import { Patient, Doctor, Clinic, Appointment, Prescription, MedicalRecord, PharmacyItem, NotificationItem, Review, QueueItem, EmergencyCase } from '../types';

export const INITIAL_CLINICS: Clinic[] = [
  {
    id: 'c1',
    name: 'Apex Healthcare Centre',
    city: 'Mumbai',
    address: 'Plot 42, Bandra Kurla Complex, Bandra East, Mumbai - 400051',
    lat: 19.0657,
    lng: 72.8686,
    distanceKm: 1.8,
    travelTimeMin: 8,
    rating: 4.9,
    reviewCount: 328,
    facilities: ['24/7 ICU', 'Advanced MRI/CT Scan', 'Robotic Surgery', 'Digital Pharmacy', 'Emergency Bay', 'Valet Parking'],
    departments: ['Cardiology', 'Neurology', 'Orthopedics', 'General Medicine'],
    doctorIds: ['d1', 'd2', 'd3', 'd4'],
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openHours: '08:00 AM - 10:00 PM',
    isOpen: true,
    liveQueueLength: 4,
    avgWaitTimeMin: 12,
    consultationFeeRange: '₹800 - ₹1,500',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: true,
    aiMatchScore: 98,
  },
  {
    id: 'c2',
    name: 'CarePulse Multispecialty Clinic',
    city: 'Bangalore',
    address: '12th Main Rd, Indiranagar, Bengaluru, Karnataka 560038',
    lat: 12.9784,
    lng: 77.6408,
    distanceKm: 2.4,
    travelTimeMin: 12,
    rating: 4.8,
    reviewCount: 245,
    facilities: ['Day Care Surgery', 'Comprehensive Diagnostics', 'Physiotherapy Wing', 'Express Pharmacy'],
    departments: ['Dermatology', 'Pediatrics', 'ENT', 'Gynaecology'],
    doctorIds: ['d5', 'd6', 'd7', 'd8'],
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    openHours: '07:30 AM - 09:00 PM',
    isOpen: true,
    liveQueueLength: 6,
    avgWaitTimeMin: 18,
    consultationFeeRange: '₹600 - ₹1,200',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 91,
  },
  {
    id: 'c3',
    name: 'Sanjeevani Polyclinic & Diagnostics',
    city: 'New Delhi',
    address: 'B-14, Greater Kailash Enclave I, New Delhi 110048',
    lat: 28.5482,
    lng: 77.2341,
    distanceKm: 3.1,
    travelTimeMin: 15,
    rating: 4.7,
    reviewCount: 189,
    facilities: ['Automated Blood Bank', 'Ultrasound Color Doppler', 'Vaccination Lounge', 'Tele-Consultation Pod'],
    departments: ['General Medicine', 'Pulmonology', 'Endocrinology', 'Gastroenterology'],
    doctorIds: ['d9', 'd10', 'd11', 'd12'],
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
    openHours: '08:00 AM - 08:30 PM',
    isOpen: true,
    liveQueueLength: 3,
    avgWaitTimeMin: 10,
    consultationFeeRange: '₹500 - ₹1,000',
    emergencyAvailable: false,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 88,
  },
  {
    id: 'c4',
    name: 'Apollo Digital Care Hub',
    city: 'Hyderabad',
    address: 'Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033',
    lat: 17.4319,
    lng: 78.4073,
    distanceKm: 4.2,
    travelTimeMin: 19,
    rating: 4.9,
    reviewCount: 412,
    facilities: ['AI Triage Lounge', 'Robotic Rehab Center', 'Genetic Screening Lab', '24x7 Emergency Trauma'],
    departments: ['Neurology', 'Cardiology', 'Oncology', 'Urology'],
    doctorIds: ['d13', 'd14', 'd15', 'd1'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    openHours: '24 Hours Open',
    isOpen: true,
    liveQueueLength: 8,
    avgWaitTimeMin: 22,
    consultationFeeRange: '₹1,000 - ₹2,000',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 94,
  },
  {
    id: 'c5',
    name: 'MetroCare SuperSpecialty Clinic',
    city: 'Chennai',
    address: 'GST Road, Guindy, Chennai, Tamil Nadu 600032',
    lat: 13.0067,
    lng: 80.2020,
    distanceKm: 5.0,
    travelTimeMin: 21,
    rating: 4.6,
    reviewCount: 164,
    facilities: ['Cardiac Cath Lab', 'Digital X-Ray Unit', 'Diabetic Care Wing', 'Home Sample Collection'],
    departments: ['Cardiology', 'Endocrinology', 'Nephrology', 'General Surgery'],
    doctorIds: ['d16', 'd17', 'd18', 'd2'],
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=800&q=80',
    openHours: '08:00 AM - 09:00 PM',
    isOpen: true,
    liveQueueLength: 5,
    avgWaitTimeMin: 14,
    consultationFeeRange: '₹700 - ₹1,400',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 85,
  },
  {
    id: 'c6',
    name: 'Zenith Wellness & Family Care',
    city: 'Pune',
    address: 'Koregaon Park Annex, Mundhwa, Pune, Maharashtra 411036',
    lat: 18.5362,
    lng: 73.8940,
    distanceKm: 2.9,
    travelTimeMin: 11,
    rating: 4.8,
    reviewCount: 290,
    facilities: ['Mind-Body Wellness Center', 'Pediatric Care Unit', 'Optical & Dental Pod', 'In-house Pharmacy'],
    departments: ['Pediatrics', 'Psychiatry', 'Ophthalmology', 'Dermatology'],
    doctorIds: ['d19', 'd20', 'd5', 'd7'],
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
    openHours: '09:00 AM - 08:00 PM',
    isOpen: true,
    liveQueueLength: 2,
    avgWaitTimeMin: 8,
    consultationFeeRange: '₹500 - ₹1,100',
    emergencyAvailable: false,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 89,
  },
  {
    id: 'c7',
    name: 'Lifeline MedCenter',
    city: 'Ahmedabad',
    address: 'SG Highway, Bodakdev, Ahmedabad, Gujarat 380054',
    lat: 23.0396,
    lng: 72.5067,
    distanceKm: 3.8,
    travelTimeMin: 16,
    rating: 4.7,
    reviewCount: 178,
    facilities: ['Dialysis Unit', 'Bone & Joint Institute', 'Skin & Laser Suite', 'Emergency Trauma Room'],
    departments: ['Orthopedics', 'Nephrology', 'Dermatology', 'General Medicine'],
    doctorIds: ['d3', 'd17', 'd6', 'd9'],
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    openHours: '08:00 AM - 09:30 PM',
    isOpen: true,
    liveQueueLength: 4,
    avgWaitTimeMin: 13,
    consultationFeeRange: '₹600 - ₹1,300',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 87,
  },
  {
    id: 'c8',
    name: 'Lotus Healthcare & Women Wellness',
    city: 'Jaipur',
    address: 'C-Scheme, Ashok Nagar, Jaipur, Rajasthan 302001',
    lat: 26.9124,
    lng: 75.7873,
    distanceKm: 4.6,
    travelTimeMin: 20,
    rating: 4.9,
    reviewCount: 310,
    facilities: ['Maternity Suite', 'Neonatal ICU', 'Gynecological Ultrasound', 'Wellness Spa'],
    departments: ['Gynaecology', 'Pediatrics', 'Endocrinology'],
    doctorIds: ['d8', 'd5', 'd11'],
    image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&w=800&q=80',
    openHours: '08:30 AM - 08:30 PM',
    isOpen: true,
    liveQueueLength: 3,
    avgWaitTimeMin: 11,
    consultationFeeRange: '₹700 - ₹1,500',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 92,
  },
  {
    id: 'c9',
    name: 'Suburban Polyclinic & Research',
    city: 'Kolkata',
    address: 'Salt Lake Sector V, Kolkata, West Bengal 700091',
    lat: 22.5726,
    lng: 88.4331,
    distanceKm: 6.1,
    travelTimeMin: 25,
    rating: 4.5,
    reviewCount: 142,
    facilities: ['Chest & Allergy Lab', 'Digital Mammography', 'Physiotherapy Gym'],
    departments: ['Pulmonology', 'Oncology', 'ENT', 'General Medicine'],
    doctorIds: ['d10', 'd14', 'd7', 'd4'],
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80',
    openHours: '09:00 AM - 08:00 PM',
    isOpen: true,
    liveQueueLength: 5,
    avgWaitTimeMin: 16,
    consultationFeeRange: '₹500 - ₹1,000',
    emergencyAvailable: false,
    insuranceAccepted: false,
    aiRecommended: false,
    aiMatchScore: 80,
  },
  {
    id: 'c10',
    name: 'NovaCare SuperSpecialty',
    city: 'Gurugram',
    address: 'Golf Course Road, Sector 54, Gurugram, Haryana 122002',
    lat: 28.4595,
    lng: 77.0266,
    distanceKm: 1.2,
    travelTimeMin: 5,
    rating: 4.9,
    reviewCount: 520,
    facilities: ['Executive Health Check Lounge', 'Advanced MRI 3T', 'Hyperbaric Oxygen Chamber', 'Private Helipad Access'],
    departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Urology', 'Gastroenterology'],
    doctorIds: ['d1', 'd2', 'd13', 'd15', 'd18'],
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    openHours: '24 Hours Open',
    isOpen: true,
    liveQueueLength: 7,
    avgWaitTimeMin: 15,
    consultationFeeRange: '₹1,200 - ₹2,500',
    emergencyAvailable: true,
    insuranceAccepted: true,
    aiRecommended: false,
    aiMatchScore: 96,
  },
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Rajesh Sharma',
    specialization: 'Cardiology',
    qualification: 'MD (General Medicine), DM (Cardiology) - AIIMS New Delhi',
    experienceYears: 18,
    languages: ['English', 'Hindi', 'Marathi'],
    rating: 4.9,
    reviewCount: 340,
    consultationFee: 1500,
    patientsServed: 14200,
    clinicIds: ['c1', 'c4', 'c10'],
    currentClinicId: 'c1',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 02:00 PM, 05:00 PM - 08:00 PM',
    vacationMode: false,
  },
  {
    id: 'd2',
    name: 'Dr. Ananya Iyer',
    specialization: 'Dermatology',
    qualification: 'MD (Dermatology, Venereology & Leprosy) - JIPMER Puducherry',
    experienceYears: 12,
    languages: ['English', 'Hindi', 'Tamil'],
    rating: 4.8,
    reviewCount: 295,
    consultationFee: 1200,
    patientsServed: 9800,
    clinicIds: ['c1', 'c5', 'c10'],
    currentClinicId: 'c1',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1594824813566-78a9327d9760?auto=format&fit=crop&w=400&q=80',
    workingHours: '10:00 AM - 04:00 PM',
    vacationMode: false,
  },
  {
    id: 'd3',
    name: 'Dr. Vikramaditya Deshmukh',
    specialization: 'Orthopedics',
    qualification: 'MS (Orthopedics), Fellowship in Joint Replacement (UK)',
    experienceYears: 15,
    languages: ['English', 'Hindi', 'Marathi', 'Gujarati'],
    rating: 4.9,
    reviewCount: 410,
    consultationFee: 1400,
    patientsServed: 11500,
    clinicIds: ['c1', 'c7', 'c10'],
    currentClinicId: 'c1',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:30 AM - 01:30 PM, 04:30 PM - 07:30 PM',
    vacationMode: false,
  },
  {
    id: 'd4',
    name: 'Dr. Meera Sengupta',
    specialization: 'General Medicine',
    qualification: 'MBBS, MD (Internal Medicine) - KGMU Lucknow',
    experienceYears: 10,
    languages: ['English', 'Hindi', 'Bengali'],
    rating: 4.7,
    reviewCount: 210,
    consultationFee: 800,
    patientsServed: 8400,
    clinicIds: ['c1', 'c9'],
    currentClinicId: 'c1',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    workingHours: '08:00 AM - 02:00 PM',
    vacationMode: false,
  },
  {
    id: 'd5',
    name: 'Dr. Kavya Reddy',
    specialization: 'Pediatrics',
    qualification: 'MD (Pediatrics), DNB, Fellowship in Neonatology',
    experienceYears: 14,
    languages: ['English', 'Hindi', 'Telugu', 'Kannada'],
    rating: 4.9,
    reviewCount: 380,
    consultationFee: 900,
    patientsServed: 12800,
    clinicIds: ['c2', 'c6', 'c8'],
    currentClinicId: 'c2',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 01:00 PM, 05:00 PM - 08:30 PM',
    vacationMode: false,
  },
  {
    id: 'd6',
    name: 'Dr. Rohan Patel',
    specialization: 'Dermatology',
    qualification: 'DVD, MD (Dermatology) - BJMC Ahmedabad',
    experienceYears: 9,
    languages: ['English', 'Hindi', 'Gujarati'],
    rating: 4.6,
    reviewCount: 165,
    consultationFee: 850,
    patientsServed: 6200,
    clinicIds: ['c2', 'c7'],
    currentClinicId: 'c2',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
    workingHours: '11:00 AM - 06:00 PM',
    vacationMode: false,
  },
  {
    id: 'd7',
    name: 'Dr. Ishaan Malhotra',
    specialization: 'ENT',
    qualification: 'MS (ENT), Fellowship in Endoscopic Sinus Surgery',
    experienceYears: 11,
    languages: ['English', 'Hindi', 'Punjabi'],
    rating: 4.8,
    reviewCount: 230,
    consultationFee: 750,
    patientsServed: 7900,
    clinicIds: ['c2', 'c6', 'c9'],
    currentClinicId: 'c2',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
    workingHours: '10:00 AM - 03:00 PM',
    vacationMode: false,
  },
  {
    id: 'd8',
    name: 'Dr. Priya Nair',
    specialization: 'Gynaecology',
    qualification: 'MD (Obstetrics & Gynaecology) - Trivandrum Medical College',
    experienceYears: 16,
    languages: ['English', 'Hindi', 'Malayalam', 'Kannada'],
    rating: 4.9,
    reviewCount: 450,
    consultationFee: 1100,
    patientsServed: 15600,
    clinicIds: ['c2', 'c8'],
    currentClinicId: 'c2',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1594824813566-78a9327d9760?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 02:00 PM, 04:00 PM - 07:00 PM',
    vacationMode: false,
  },
  {
    id: 'd9',
    name: 'Dr. Devendra Verma',
    specialization: 'General Medicine',
    qualification: 'MD (Internal Medicine) - Maulana Azad Medical College',
    experienceYears: 20,
    languages: ['English', 'Hindi'],
    rating: 4.7,
    reviewCount: 310,
    consultationFee: 700,
    patientsServed: 18000,
    clinicIds: ['c3', 'c7'],
    currentClinicId: 'c3',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    workingHours: '08:30 AM - 02:00 PM',
    vacationMode: false,
  },
  {
    id: 'd10',
    name: 'Dr. Sunita Choudhury',
    specialization: 'Pulmonology',
    qualification: 'MD (Pulmonary Medicine), DTCD - IPGMER Kolkata',
    experienceYears: 13,
    languages: ['English', 'Hindi', 'Bengali'],
    rating: 4.8,
    reviewCount: 260,
    consultationFee: 950,
    patientsServed: 9100,
    clinicIds: ['c3', 'c9'],
    currentClinicId: 'c3',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    workingHours: '10:00 AM - 04:00 PM',
    vacationMode: false,
  },
  {
    id: 'd11',
    name: 'Dr. Aditya Agarwal',
    specialization: 'Endocrinology',
    qualification: 'DM (Endocrinology) - PGI Chandigarh',
    experienceYears: 15,
    languages: ['English', 'Hindi'],
    rating: 4.9,
    reviewCount: 320,
    consultationFee: 1300,
    patientsServed: 10400,
    clinicIds: ['c3', 'c8'],
    currentClinicId: 'c3',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 01:00 PM, 05:00 PM - 08:00 PM',
    vacationMode: false,
  },
  {
    id: 'd12',
    name: 'Dr. Vivek Kulkarni',
    specialization: 'Gastroenterology',
    qualification: 'DM (Gastroenterology) - Seth GS Medical College Mumbai',
    experienceYears: 14,
    languages: ['English', 'Hindi', 'Marathi'],
    rating: 4.8,
    reviewCount: 280,
    consultationFee: 1400,
    patientsServed: 8900,
    clinicIds: ['c3'],
    currentClinicId: 'c3',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
    workingHours: '11:00 AM - 05:00 PM',
    vacationMode: false,
  },
  {
    id: 'd13',
    name: 'Dr. Siddhartha Rao',
    specialization: 'Neurology',
    qualification: 'DM (Neurology), Fellowship in Stroke & Epilepsy (USA)',
    experienceYears: 19,
    languages: ['English', 'Hindi', 'Telugu'],
    rating: 5.0,
    reviewCount: 510,
    consultationFee: 1800,
    patientsServed: 16500,
    clinicIds: ['c4', 'c10'],
    currentClinicId: 'c4',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 03:00 PM',
    vacationMode: false,
  },
  {
    id: 'd14',
    name: 'Dr. Sneha Chatterjee',
    specialization: 'Oncology',
    qualification: 'MD, DM (Medical Oncology) - Tata Memorial Centre',
    experienceYears: 17,
    languages: ['English', 'Hindi', 'Bengali'],
    rating: 4.9,
    reviewCount: 390,
    consultationFee: 2000,
    patientsServed: 11200,
    clinicIds: ['c4', 'c9'],
    currentClinicId: 'c4',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1594824813566-78a9327d9760?auto=format&fit=crop&w=400&q=80',
    workingHours: '10:00 AM - 04:00 PM',
    vacationMode: false,
  },
  {
    id: 'd15',
    name: 'Dr. Neeraj Bansal',
    specialization: 'Urology',
    qualification: 'MCh (Urology) - AIIMS New Delhi',
    experienceYears: 13,
    languages: ['English', 'Hindi'],
    rating: 4.7,
    reviewCount: 225,
    consultationFee: 1300,
    patientsServed: 7800,
    clinicIds: ['c4', 'c10'],
    currentClinicId: 'c4',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:30 AM - 02:30 PM',
    vacationMode: false,
  },
  {
    id: 'd16',
    name: 'Dr. Arvind Swaminathan',
    specialization: 'Cardiology',
    qualification: 'DM (Cardiology) - Madras Medical College',
    experienceYears: 21,
    languages: ['English', 'Tamil', 'Hindi'],
    rating: 4.9,
    reviewCount: 480,
    consultationFee: 1600,
    patientsServed: 19500,
    clinicIds: ['c5'],
    currentClinicId: 'c5',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
    workingHours: '08:30 AM - 01:30 PM, 04:30 PM - 07:30 PM',
    vacationMode: false,
  },
  {
    id: 'd17',
    name: 'Dr. Tarun Joshi',
    specialization: 'Nephrology',
    qualification: 'DM (Nephrology) - KEM Hospital Mumbai',
    experienceYears: 11,
    languages: ['English', 'Hindi', 'Gujarati'],
    rating: 4.7,
    reviewCount: 190,
    consultationFee: 1100,
    patientsServed: 6400,
    clinicIds: ['c5', 'c7'],
    currentClinicId: 'c5',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
    workingHours: '10:00 AM - 03:00 PM',
    vacationMode: false,
  },
  {
    id: 'd18',
    name: 'Dr. Shalini Saxena',
    specialization: 'General Surgery',
    qualification: 'MS (General Surgery), FMAS, FIAGES',
    experienceYears: 16,
    languages: ['English', 'Hindi'],
    rating: 4.8,
    reviewCount: 310,
    consultationFee: 1250,
    patientsServed: 10800,
    clinicIds: ['c5', 'c10'],
    currentClinicId: 'c5',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 02:00 PM',
    vacationMode: false,
  },
  {
    id: 'd19',
    name: 'Dr. Nikhil Bhardwaj',
    specialization: 'Psychiatry',
    qualification: 'MD (Psychiatry) - NIMHANS Bengaluru',
    experienceYears: 10,
    languages: ['English', 'Hindi', 'Marathi'],
    rating: 4.9,
    reviewCount: 275,
    consultationFee: 1000,
    patientsServed: 5900,
    clinicIds: ['c6'],
    currentClinicId: 'c6',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    workingHours: '11:00 AM - 06:00 PM',
    vacationMode: false,
  },
  {
    id: 'd20',
    name: 'Dr. Rashmi Kapoor',
    specialization: 'Ophthalmology',
    qualification: 'MS (Ophthalmology), Fellowship in Cornea & Refractive Surgery',
    experienceYears: 12,
    languages: ['English', 'Hindi', 'Punjabi'],
    rating: 4.8,
    reviewCount: 220,
    consultationFee: 800,
    patientsServed: 8700,
    clinicIds: ['c6'],
    currentClinicId: 'c6',
    isAvailable: true,
    avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
    workingHours: '09:00 AM - 01:00 PM, 04:00 PM - 07:00 PM',
    vacationMode: false,
  },
];

// Generate 50 Patients
const INDIAN_FIRST_NAMES_MALE = ['Aarav', 'Rohan', 'Rajesh', 'Devendra', 'Ishaan', 'Vivek', 'Vikram', 'Aditya', 'Siddhartha', 'Neeraj', 'Arvind', 'Tarun', 'Nikhil', 'Gaurav', 'Manish', 'Sanjay', 'Amit', 'Deepak', 'Kunal', 'Abhishek', 'Varun', 'Yash', 'Rahul', 'Pranav', 'Suresh'];
const INDIAN_FIRST_NAMES_FEMALE = ['Ananya', 'Priya', 'Kavya', 'Sunita', 'Meera', 'Sneha', 'Pooja', 'Neha', 'Shalini', 'Rashmi', 'Divya', 'Ritu', 'Simran', 'Tanvi', 'Swati', 'Priti', 'Anjali', 'Richa', 'Nisha', 'Archana', 'Monika', 'Kriti', 'Sonali', 'Payal', 'Isha'];
const INDIAN_LAST_NAMES = ['Sharma', 'Iyer', 'Gupta', 'Patel', 'Reddy', 'Nair', 'Rao', 'Verma', 'Malhotra', 'Joshi', 'Deshmukh', 'Kulkarni', 'Sengupta', 'Choudhury', 'Chawla', 'Agarwal', 'Chatterjee', 'Bansal', 'Swaminathan', 'Saxena', 'Kapoor', 'Bhardwaj', 'Kaur', 'Singh', 'Desai'];

export const GENERATED_PATIENTS: Patient[] = Array.from({ length: 50 }, (_, i) => {
  const isMale = i % 2 === 0;
  const firstName = isMale ? INDIAN_FIRST_NAMES_MALE[i % 25] : INDIAN_FIRST_NAMES_FEMALE[i % 25];
  const lastName = INDIAN_LAST_NAMES[(i * 3) % 25];
  const name = `${firstName} ${lastName}`;
  const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];
  const cities = ['Mumbai', 'Bangalore', 'New Delhi', 'Hyderabad', 'Chennai', 'Pune', 'Ahmedabad', 'Jaipur', 'Kolkata', 'Gurugram'];

  return {
    id: `p${i + 1}`,
    name,
    age: 20 + ((i * 7) % 55),
    gender: isMale ? 'Male' : 'Female',
    phone: `+91 98${Math.floor(10000000 + (i * 8765432) % 89999999)}`,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}${i + 1}@gmail.com`,
    bloodGroup: bloodGroups[i % bloodGroups.length],
    location: `${10 + (i % 80)} Sector ${i + 1}`,
    city: cities[i % cities.length],
    emergencyContact: `+91 99${Math.floor(10000000 + (i * 9876543) % 89999999)}`,
    medicalHistory: i % 3 === 0 ? ['Hypertension', 'Mild Asthma'] : i % 5 === 0 ? ['Type 2 Diabetes'] : i % 7 === 0 ? ['Thyroid Disorders'] : ['No chronic illnesses recorded'],
    allergies: i % 4 === 0 ? ['Penicillin'] : i % 6 === 0 ? ['Dust Mites', 'Pollen'] : ['None'],
    activePrescriptionsCount: 1 + (i % 3),
    riskScore: i % 10 === 0 ? 'High' : i % 4 === 0 ? 'Moderate' : 'Low',
    avatar: isMale 
      ? `https://images.unsplash.com/photo-${1530000000000 + (i * 100000)}?auto=format&fit=crop&w=200&q=80`
      : `https://images.unsplash.com/photo-${1540000000000 + (i * 100000)}?auto=format&fit=crop&w=200&q=80`,
  };
});

// Primary active patient for current logged in view
export const CURRENT_PATIENT: Patient = GENERATED_PATIENTS[0]; // Aarav Sharma

// Primary doctor for current logged in doctor view
export const CURRENT_DOCTOR: Doctor = INITIAL_DOCTORS[0]; // Dr. Rajesh Sharma

// 500 Appointments generator
const STATUSES: Appointment['status'][] = ['Confirmed', 'In-Queue', 'Completed', 'Cancelled', 'Priority', 'Emergency'];
const SYMPTOM_LISTS = [
  ['Chest discomfort', 'Shortness of breath', 'Mild palpitation'],
  ['Skin rash', 'Itching', 'Red spots on arm'],
  ['Joint pain', 'Knee swelling', 'Morning stiffness'],
  ['Seasonal fever', 'Fatigue', 'Headache'],
  ['Persistent cough', 'Throat irritation'],
  ['Stomach ache', 'Acidity', 'Nausea'],
  ['Migraine headache', 'Dizziness'],
  ['Childhood fever', 'Loss of appetite'],
  ['Routine health checkup', 'BP Monitoring'],
];

export const GENERATED_APPOINTMENTS: Appointment[] = Array.from({ length: 500 }, (_, i) => {
  const patient = GENERATED_PATIENTS[i % GENERATED_PATIENTS.length];
  const doctor = INITIAL_DOCTORS[i % INITIAL_DOCTORS.length];
  const clinic = INITIAL_CLINICS.find(c => c.id === doctor.currentClinicId) || INITIAL_CLINICS[0];
  const dateObj = new Date();
  dateObj.setDate(dateObj.getDate() + (i % 14) - 7); // Range from 7 days ago to 7 days ahead
  const formattedDate = dateObj.toISOString().split('T')[0];

  const hour = 9 + (i % 8);
  const minute = (i % 4) * 15;
  const timeSlot = `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}`;

  const status = i === 0 ? 'In-Queue' : i === 1 ? 'Confirmed' : i === 2 ? 'Priority' : STATUSES[i % STATUSES.length];

  return {
    id: `apt-${i + 1}`,
    patientId: patient.id,
    patientName: patient.name,
    doctorId: doctor.id,
    doctorName: doctor.name,
    specialization: doctor.specialization,
    clinicId: clinic.id,
    clinicName: clinic.name,
    date: formattedDate,
    timeSlot,
    tokenNumber: (i % 25) + 1,
    status,
    priorityLevel: i % 15 === 0 ? 'Emergency' : i % 5 === 0 ? 'Urgent' : 'Standard',
    symptoms: SYMPTOM_LISTS[i % SYMPTOM_LISTS.length],
    fee: doctor.consultationFee,
    isAiRecommendedSlot: i % 3 === 0,
  };
});

// 100 Pharmacy Items
const MEDICINE_NAMES = [
  { name: 'Paracetamol 650mg (Dolo)', category: 'Analgesics' },
  { name: 'Amoxicillin 500mg (Mox 500)', category: 'Antibiotics' },
  { name: 'Metformin 500mg (Glycomet)', category: 'Antidiabetic' },
  { name: 'Atorvastatin 10mg (Atorva)', category: 'Cardiovascular' },
  { name: 'Azithromycin 500mg (Azee)', category: 'Antibiotics' },
  { name: 'Pantoprazole 40mg (Pan 40)', category: 'Gastroenterology' },
  { name: 'Cetirizine 10mg (Okacet)', category: 'Antihistamines' },
  { name: 'Montelukast 10mg (Montair)', category: 'Respiratory' },
  { name: 'Telmisartan 40mg (Telma)', category: 'Cardiovascular' },
  { name: 'Vitamin C + Zinc (Celin)', category: 'Supplements' },
  { name: 'Ibuprofen 400mg (Brufen)', category: 'NSAIDs' },
  { name: 'Omeprazole 20mg (Omez)', category: 'Gastroenterology' },
  { name: 'Amlodipine 5mg (Stamlo)', category: 'Cardiovascular' },
  { name: 'Levothyroxine 50mcg (Thyronorm)', category: 'Endocrinology' },
  { name: 'Ciprofloxacin 500mg (Ciprolet)', category: 'Antibiotics' },
];

export const GENERATED_PHARMACY_ITEMS: PharmacyItem[] = Array.from({ length: 100 }, (_, i) => {
  const base = MEDICINE_NAMES[i % MEDICINE_NAMES.length];
  const stock = i % 12 === 0 ? 8 : i % 5 === 0 ? 25 : 120 + ((i * 17) % 300);
  const minThreshold = 30;

  return {
    id: `ph-${i + 1}`,
    name: `${base.name} - Batch #${100 + i}`,
    category: base.category,
    batchNumber: `BAT-2026-${(1000 + i)}`,
    stockQuantity: stock,
    minThreshold,
    expiryDate: `2027-0${(i % 9) + 1}-15`,
    pricePerUnit: 15 + ((i * 7) % 180),
    aiDemandForecast: stock < minThreshold ? 'Critical' : i % 3 === 0 ? 'High' : 'Normal',
    aiPredictedRestockDays: stock < minThreshold ? 2 : 14,
    manufacturer: i % 2 === 0 ? 'Sun Pharma India' : i % 3 === 0 ? 'Cipla Labs' : 'Dr. Reddy Labs',
  };
});

// Prescriptions & Medical Records
export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-1',
    appointmentId: 'apt-1',
    patientId: 'p1',
    patientName: 'Aarav Sharma',
    doctorId: 'd1',
    doctorName: 'Dr. Rajesh Sharma',
    clinicName: 'Apex Healthcare Centre',
    date: '2026-08-01',
    diagnosis: 'Mild Essential Hypertension & Sinus Tachycardia',
    medicines: [
      { name: 'Telmisartan 40mg', dosage: '1 tablet daily (Morning)', duration: '30 Days', instructions: 'Take after breakfast' },
      { name: 'Metoprolol 25mg', dosage: '1 tablet daily (Night)', duration: '30 Days', instructions: 'Take with warm water' },
    ],
    labTestsRecommended: ['Lipid Profile', 'ECG 12-Lead', 'Serum Creatinine'],
    followUpDate: '2026-08-15',
  },
  {
    id: 'rx-2',
    appointmentId: 'apt-2',
    patientId: 'p1',
    patientName: 'Aarav Sharma',
    doctorId: 'd2',
    doctorName: 'Dr. Ananya Iyer',
    clinicName: 'Apex Healthcare Centre',
    date: '2026-07-20',
    diagnosis: 'Acute Contact Dermatitis',
    medicines: [
      { name: 'Cetirizine 10mg', dosage: '1 tablet at bedtime', duration: '7 Days', instructions: 'May cause mild drowsiness' },
      { name: 'Hydrocortisone 1% Cream', dosage: 'Apply twice daily', duration: '5 Days', instructions: 'External use only' },
    ],
    followUpDate: '2026-07-28',
  },
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'mr-1',
    patientId: 'p1',
    patientName: 'Aarav Sharma',
    type: 'Digital Prescription',
    title: 'Cardiology Consultation & Rx',
    doctorName: 'Dr. Rajesh Sharma',
    clinicName: 'Apex Healthcare Centre',
    date: '2026-08-01',
    fileSize: '1.2 MB',
    downloadUrl: '#',
    summary: 'Hypertension management plan & BP monitor prescription.',
  },
  {
    id: 'mr-2',
    patientId: 'p1',
    patientName: 'Aarav Sharma',
    type: 'Lab Report',
    title: 'Comprehensive Lipid & Fasting Blood Sugar',
    doctorName: 'Dr. Devendra Verma',
    clinicName: 'Sanjeevani Polyclinic',
    date: '2026-07-15',
    fileSize: '2.8 MB',
    downloadUrl: '#',
    summary: 'Total Cholesterol: 195 mg/dL (Normal). HbA1c: 5.6%.',
  },
  {
    id: 'mr-3',
    patientId: 'p1',
    patientName: 'Aarav Sharma',
    type: 'Medical Image',
    title: 'Chest X-Ray Digital Scan (PA View)',
    doctorName: 'Dr. Sunita Choudhury',
    clinicName: 'Apex Healthcare Centre',
    date: '2026-06-10',
    fileSize: '14.5 MB',
    downloadUrl: '#',
    summary: 'Clear lung fields. Normal cardiac size.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    type: 'earlier_slot',
    title: 'Earlier Appointment Slot Available! ⚡',
    message: 'Patient cancelled a 02:10 PM slot with Dr. Rajesh Sharma at Apex Healthcare. Would you like to shift from your 04:30 PM slot?',
    timestamp: '10 mins ago',
    read: false,
    actionableSlot: '02:10 PM',
  },
  {
    id: 'n2',
    type: 'queue_update',
    title: 'Live Queue Progress Update',
    message: 'Your token #04 is now next in line! Est. wait time: ~6 mins.',
    timestamp: '25 mins ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'medicine_reminder',
    title: 'Daily Prescription Reminder 💊',
    message: 'Time for your Telmisartan 40mg post-lunch dose.',
    timestamp: '2 hours ago',
    read: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'r1',
    clinicId: 'c1',
    patientName: 'Kavya Reddy',
    rating: 5,
    comment: 'The AI live queue estimate was spot on! Barely waited 8 minutes. Dr. Rajesh Sharma was incredibly patient and attentive.',
    date: '2026-08-02',
  },
  {
    id: 'r2',
    clinicId: 'c1',
    patientName: 'Rohan Gupta',
    rating: 5,
    comment: 'State of the art facility. Glassmorphic digital tokens and instant WhatsApp prescriptions made the experience seamless.',
    date: '2026-07-29',
  },
];

export const INITIAL_EMERGENCY_CASES: EmergencyCase[] = [
  {
    id: 'em-101',
    patientName: 'Vikram Sengupta',
    age: 58,
    condition: 'Acute Angina / Chest Pain',
    priority: 'Critical',
    assignedDoctorId: 'd1',
    assignedDoctorName: 'Dr. Rajesh Sharma',
    clinicName: 'Apex Healthcare Centre',
    etaMinutes: 4,
    status: 'Triage',
  },
  {
    id: 'em-102',
    patientName: 'Priya Patel',
    age: 34,
    condition: 'High Fever & Acute Dehydration',
    priority: 'Severe',
    assignedDoctorId: 'd4',
    assignedDoctorName: 'Dr. Meera Sengupta',
    clinicName: 'Apex Healthcare Centre',
    etaMinutes: 12,
    status: 'En Route',
  },
];
